---
- name: Create Nodes and Bucket
  hosts: tags_Name_jd*
  gather_facts: true
  become: true
  vars_files:
    - "vars.yaml"

  roles:
    - node_create
    - bucket_create
    - first_role
    - second_role
    - send_logs
